// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import BookmarktipController from "./bookmarktip_controller"
application.register("bookmarktip", BookmarktipController)

import CityAutocompleteController from "./city_autocomplete_controller"
application.register("city-autocomplete", CityAutocompleteController)

import CityController from "./city_controller"
application.register("city", CityController)

import EndDateController from "./end_date_controller"
application.register("end-date", EndDateController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HiddenFieldController from "./hidden_field_controller"
application.register("hidden-field", HiddenFieldController)

import HiddenPanelController from "./hidden_panel_controller"
application.register("hidden-panel", HiddenPanelController)

import MapController from "./map_controller"
application.register("map", MapController)

import PasswordChangeController from "./password_change_controller"
application.register("password-change", PasswordChangeController)

import SearchPeopleController from "./search_people_controller"
application.register("search-people", SearchPeopleController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
